linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  misspell:
    locale: US
run:
  timeout: 2m
